#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
GUARD_DIR="$ROOT_DIR/.proxybox-guard"
REQUEST_FILE="$GUARD_DIR/https-request"
RESPONSE_FILE="$GUARD_DIR/https-response"
LOCK_DIR="$GUARD_DIR/https.lock"
MANAGED_HEADER="# ProxyBox HTTPS - generated by deploy/docker-https-apply.sh"

request_id=""

sanitize() {
    printf '%s' "$1" | tr '\n\r' '  ' | cut -c1-800
}

kv_get() {
    local key="$1" file="$2"
    awk -F= -v key="$key" '$1 == key { print substr($0, index($0, "=") + 1) }' "$file" \
        | tail -n 1
}

env_value() {
    local key="$1"
    [ -f "$ENV_FILE" ] || return 0
    kv_get "$key" "$ENV_FILE"
}

write_response() {
    local state="$1" code="$2" message="$3" public_ip="${4:-}" caddy="${5:-}"
    mkdir -p "$GUARD_DIR"
    local tmp
    tmp="$(mktemp "$GUARD_DIR/https-response.XXXXXX")"
    {
        printf 'request_id=%s\n' "$request_id"
        printf 'state=%s\n' "$state"
        printf 'code=%s\n' "$code"
        printf 'message=%s\n' "$(sanitize "$message")"
        printf 'public_ip=%s\n' "$public_ip"
        printf 'caddy=%s\n' "$caddy"
        printf 'last_run=%s\n' "$(date +%s)"
    } > "$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$RESPONSE_FILE"
}

fail() {
    write_response failed "$1" "$2" "${3:-}" "${4:-}"
    exit 0
}

run_cmd() {
    local output
    if ! output="$("$@" 2>&1)"; then
        fail cmd_failed "$* failed: $output"
    fi
    printf '%s' "$output"
}

validate_domain() {
    local domain="$1"
    if ! printf '%s' "$domain" \
        | grep -Eq '^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$'; then
        fail invalid_domain "$domain"
    fi
    if [ "${#domain}" -lt 4 ] || [ "${#domain}" -gt 253 ]; then
        fail invalid_domain "$domain"
    fi
}

public_ip() {
    curl -4 -fsS --max-time 8 https://api4.ipify.org 2>/dev/null \
        || curl -4 -fsS --max-time 8 https://ipv4.icanhazip.com 2>/dev/null \
        || true
}

install_caddy() {
    if command -v caddy >/dev/null 2>&1; then
        printf 'already'
        return
    fi

    export DEBIAN_FRONTEND=noninteractive
    run_cmd apt-get update -qq >/dev/null
    run_cmd apt-get install -y -qq \
        debian-keyring \
        debian-archive-keyring \
        apt-transport-https \
        ca-certificates \
        curl \
        gpg >/dev/null

    local keyring="/usr/share/keyrings/caddy-stable-archive-keyring.gpg"
    local key_tmp repo_tmp
    key_tmp="$(mktemp)"
    repo_tmp="$(mktemp)"
    run_cmd curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key -o "$key_tmp" >/dev/null
    run_cmd gpg --batch --yes --dearmor -o "$keyring" "$key_tmp" >/dev/null
    run_cmd curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt -o "$repo_tmp" >/dev/null
    run_cmd install -m 0644 "$repo_tmp" /etc/apt/sources.list.d/caddy-stable.list >/dev/null
    rm -f "$key_tmp" "$repo_tmp"
    run_cmd apt-get update -qq >/dev/null
    run_cmd apt-get install -y -qq caddy >/dev/null
    printf 'installed'
}

write_caddyfile() {
    local domain="$1" admin_port="$2"
    mkdir -p /etc/caddy
    if [ -s /etc/caddy/Caddyfile ] && ! grep -qF "$MANAGED_HEADER" /etc/caddy/Caddyfile; then
        if ! grep -q "/usr/share/caddy" /etc/caddy/Caddyfile \
            || grep -q "reverse_proxy" /etc/caddy/Caddyfile; then
            fail caddyfile_conflict \
                "/etc/caddy/Caddyfile already exists and is not managed by ProxyBox; refusing to overwrite user Caddy config"
        fi
    fi

    local tmp
    tmp="$(mktemp /etc/caddy/Caddyfile.proxybox.XXXXXX)"
    cat > "$tmp" <<EOF
$MANAGED_HEADER
$domain {
    encode gzip zstd

    reverse_proxy 127.0.0.1:$admin_port {
        header_up X-Forwarded-Proto https
        header_up X-Forwarded-Host {http.request.host}
    }
}
EOF
    chmod 644 "$tmp"
    mv "$tmp" /etc/caddy/Caddyfile
    run_cmd caddy validate --config /etc/caddy/Caddyfile >/dev/null
}

open_firewall() {
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow 80/tcp >/dev/null 2>&1 || true
        ufw allow 443/tcp >/dev/null 2>&1 || true
    fi
    if command -v firewall-cmd >/dev/null 2>&1 \
        && systemctl is-active firewalld >/dev/null 2>&1; then
        firewall-cmd --add-service=http --permanent >/dev/null 2>&1 || true
        firewall-cmd --add-service=https --permanent >/dev/null 2>&1 || true
        firewall-cmd --reload >/dev/null 2>&1 || true
    fi
}

reload_caddy() {
    run_cmd systemctl enable --now caddy >/dev/null
    if ! systemctl reload caddy >/dev/null 2>&1; then
        run_cmd systemctl restart caddy >/dev/null
    fi
}

main() {
    mkdir -p "$GUARD_DIR"
    chmod 700 "$GUARD_DIR"

    if ! mkdir "$LOCK_DIR" 2>/dev/null; then
        exit 0
    fi
    trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT

    [ -r "$REQUEST_FILE" ] || fail docker_helper_failed "request file not readable"

    request_id="$(kv_get request_id "$REQUEST_FILE")"
    local domain admin_port requested_admin_port detected_ip resolved_ips caddy_result
    domain="$(kv_get domain "$REQUEST_FILE")"
    requested_admin_port="$(kv_get admin_port "$REQUEST_FILE")"
    [ -n "$request_id" ] || request_id="unknown"
    admin_port="$(env_value PROXYBOX_ADMIN_PORT)"
    [ -n "$admin_port" ] || fail docker_helper_failed "PROXYBOX_ADMIN_PORT is missing from .env"

    validate_domain "$domain"
    if [ -n "$requested_admin_port" ] && [ "$requested_admin_port" != "$admin_port" ]; then
        fail invalid_port "request admin_port does not match this install"
    fi
    case "$admin_port" in
        ''|*[!0-9]*) fail invalid_port "$admin_port" ;;
    esac
    if [ "$admin_port" -lt 1 ] || [ "$admin_port" -gt 65535 ]; then
        fail invalid_port "$admin_port"
    fi

    detected_ip="$(public_ip)"
    [ -n "$detected_ip" ] || fail cmd_failed "could not detect VPS public IP"

    resolved_ips="$(getent ahostsv4 "$domain" | awk '{print $1}' | sort -u | tr '\n' ' ')"
    [ -n "$resolved_ips" ] || fail dns_no_answer "$domain did not resolve" "$detected_ip"
    if ! printf '%s\n' "$resolved_ips" | tr ' ' '\n' | grep -Fxq "$detected_ip"; then
        fail dns_mismatch "$domain -> $resolved_ips but VPS public IP = $detected_ip" "$detected_ip"
    fi

    caddy_result="$(install_caddy)"
    open_firewall
    write_caddyfile "$domain" "$admin_port"
    reload_caddy
    write_response success ok "HTTPS enabled" "$detected_ip" "$caddy_result"
}

main "$@"
